FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Finances.API/Finances.API.csproj", "Finances.API/"]
COPY ["Finances.Application/Finances.Application.csproj", "Finances.Application/"]
COPY ["Finances.Domain/Finances.Domain.csproj", "Finances.Domain/"]
COPY ["OneMoney.Common/OneMoney.Common.csproj", "OneMoney.Common/"]
COPY ["Finances.Infrastructure/Finances.Infrastructure.csproj", "Finances.Infrastructure/"]
RUN dotnet restore "Finances.API/Finances.API.csproj"
COPY . .
WORKDIR "/src/Finances.API"
RUN dotnet build "./Finances.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Finances.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Finances.API.dll"]
